query_app/urls.py
from django.urls import path
from query_app import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "query_app"
urlpatterns = [
    
    
    # ------------ e-mail ----------
    path('activate-user/<uidb64>/<token>',views.activate_user, name='activate'),
    
    # -------login----------
    
    path('',views.loginPage, name = 'login-page' ),
    path('login/<str:s>/',views.loginPage_Revert, name = 'login-page-revert' ),
    path('logout/',views.logoutPage, name = 'logout-page' ),
    path('register/',views.registerPage, name = 'register-page' ),
    
    # path('extract/<int:id>/', views.extract, name = 'extract'),
    # path('Reports/<str:region>/', views.home, name = 'home'),
    
    # ----- admin -----
    
    # path('RGadmin/', views.base_html_Admin, name = 'base_html_Admin'),
    
    # ----- normal users ------  
    
      
    path('extract/<int:id>/', views.extract, name = 'extract'),
    path('fetch_data/<int:id>/', views.fetch_data, name = 'fetch_data'),
    
    
    path('Reports/<str:region>/', views.base_html_region, name = 'base_html_region'),
    path('AjaxReports/<int:id>/', views.get_Ajax_LastRun, name = 'get_Ajax_LastRun'),
    # path('AjaxReports/', views.get_Ajax_LastRun, name = 'get_Ajax_LastRun'),
   
    path('home/', views.base_html, name = 'base_html'),
    
    # path('user/', views.base_html_User, name = 'base_html_User'),
    
    # -----------------Reports---------------------
    
    # path('insert_report/', views.insert_report, name = 'insert_report'),
    path('manage_reports/', views.list_reports, name = 'manage_reports'),
    path('delete_report/<int:id>/', views.delete_report, name='delete_report'),
    path('manage_reports/<int:id>/', views.list_reports, name = 'manage_reports_update'),
    
    # -------------------Regions---------------------
    
    path('manage_regions/', views.list_regions, name = 'manage_regions'),
    path('delete_region/<str:region>/', views.delete_region, name='delete_region'),
    path('manage_regions/<str:region>/', views.list_regions, name = 'manage_regions_update'),
    
    
    # --------------------Users-----------------------
    
    path('manage_users/', views.list_users, name = 'manage_users'),
    path('delete_user/<int:id>/', views.delete_user, name='delete_user'),
    path('manage_users/<int:id>/', views.list_users, name = 'manage_users_update'),
    path('pending_user_request/', views.pending_user_request, name = 'pending_user_request'),
    path('accept_user_request/<int:id>', views.accept_user_request, name = 'accept_user_request'),
    path('reject_user_request/<int:id>', views.reject_user_request, name = 'reject_user_request'),
    # path('user_region_request_edit/', views.user_region_request_edit, name = 'user_region_request_edit'),
]

urlpatterns += staticfiles_urlpatterns()

rg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('query_app.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()

templates/base_html.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
  	<title>Reporter Genie</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	

    <link rel="stylesheet" href= "{% static 'css/search.css' %}">
	<link rel="stylesheet" href= "{% static 'css/style.css' %}">
    <link rel="stylesheet" href= "{% static 'Home.css' %}">
    <link rel="stylesheet" href= "{% static 'manage_users.css' %}">
    <link rel="stylesheet" href= "{% static 'manage_regions.css' %}">
    <link rel="stylesheet" href= "{% static 'pending-user.css' %}">

    



    

	</head>
	<body>
			{% comment %} {% for i in user %}
				<h1>{{i}}</h1>
				{% endfor %} {% endcomment %}
		

	<section class="">

		<div class="container">
			<nav class="navbar navbar-expand-lg ftco_navbar ftco-navbar-light" id="ftco-navbar">
		    <div class="container">
		    	<a class="navbar-brand" href="{% url 'query_app:base_html' %}">reporter genie <i class="fa fa-edit genie-icon"></i>  </a>
				{% comment %} <i class="fa fa-edit genie-icon"></i> {% endcomment %}
		      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
		        <span class="fa fa-bars"></span> Menu
		      </button>
		      <div class="collapse navbar-collapse" id="ftco-nav">
		        <ul class="navbar-nav ml-auto mr-md-3">
		        	<li class="nav-item active"><a href="{% url 'query_app:base_html' %}" class="nav-link">Home</a></li>

		        	<li class="dropdown nav-item d-md-flex align-items-center">
						<a href="#" class="dropdown-toggle nav-link d-flex align-items-center justify-content-center nav-link" id="dropdown04" data-toggle="dropdown" aria-expanded="false">
						  Reports
						  <b class="caret"></b>
						</a>
                        
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown04">
                            {% for region in request.user.regions.all%}
						  <a href="{% url 'query_app:base_html_region' region %}" class="dropdown-item">{{ region }}</a>
                            {% endfor %}
                        </div>
                        
					</li>

                    {% if request.user.is_superuser or request.user.is_staff %}

		        	<li class="dropdown nav-item d-md-flex align-items-center">
						<a href="#" class="dropdown-toggle nav-link d-flex align-items-center justify-content-center nav-link" id="dropdown04" data-toggle="dropdown" aria-expanded="false">
						  Tools
						  <b class="caret"></b>
						</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown04">
						  <a href="#" class="dropdown-item">DB Refresh</a>

						</div>
					</li>

                    {% endif %}

		        	{% if request.user.is_superuser %}

					<li class="dropdown nav-item d-md-flex align-items-center">
						<a href="#" class="dropdown-toggle nav-link d-flex align-items-center justify-content-center nav-link" id="dropdown04" data-toggle="dropdown" aria-expanded="false">
						  Edit
						  <b class="caret"></b>
						</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown04">
						  <a href="{% url 'query_app:manage_users' %}" class="dropdown-item">Manage Users</a>
						  <a href="{% url 'query_app:pending_user_request' %}" class="dropdown-item">Pending Request</a>
						  <a href="{% url 'query_app:manage_regions' %}" class="dropdown-item">Manage Regions</a>
						  <a href="{% url 'query_app:manage_reports' %}" class="dropdown-item">Manage Reports</a>
						</div>
					</li>


                    {% endif %}
                    <li class="dropdown nav-item d-md-flex align-items-center">
                    {% block search %}
                    {% endblock %}
                    </li>
                    

		          <li class="dropdown nav-item d-md-flex align-items-center">
                <a href="#" class="dropdown-toggle nav-link d-flex align-items-center justify-content-center icon-cart nav-link " id="dropdown04" data-toggle="dropdown" aria-expanded="false">
                  <i class="fa fa-user"></i>
                  <b class="caret"></b>
                </a>
                <div class="dropdown-menu dropdown-menu-right header-logout" aria-labelledby="dropdown04">
                  <p class="dropdown-item" style="pointer-events: none; margin-bottom:0;">Hello, {{request.user}}</p>
                  <a href="{% url 'query_app:logout-page' %}" class="dropdown-item">Logout</a>
  
                </div>
              </li>
		        </ul>
		      </div>
		    </div>
		  </nav>
    <!-- END nav -->
  </div>

  {% block content %}
  {% endblock %}











	</section>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    {% comment %} <script src="{% static 'js/popper.js' %}"></script> {% endcomment %}
    {% comment %} <script src="{% static 'js/bootstrap.min.js' %}"></script> {% endcomment %}
    <script src="{% static 'js/main.js' %}"></script>
	

	


	</body>
</html>

templates/base_html_old.html
{% load static %}
<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Reporter Genie</title>
    {% comment %} <link rel="stylesheet" href="base_html.css"> {% endcomment %}
    
    <link rel="stylesheet"  type = "text/css" href="{% static 'style_RG.css' %}">
    <link rel="stylesheet"  type = "text/css" href="{% static 'Home.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    
  </head>
  <body style="font-family: system-ui; overflow-x: hidden;">
    <div class="container-fluid">
        <div class="row flex-nowrap bg-light">
            <div class="col-auto col-md-3 col-xl-2 px-0" style="background-color: lightseagreen">
                <div style="display: flex;
                justify-content: center;
                margin-top: 22px;">

            <a href = "{% url 'query_app:base_html' %}">
                <div style = "font-weight: bold;
                width: 112px;
                height: 112px;
                justify-content: center;
                text-align: center;
                font-size: 56px;
                background-color: aliceblue;
                color: lightseagreen;
                border-radius: 60px;
                box-shadow: 0px 0px 3px 2.5px lightgrey;">
                
                    <big class = "d-none d-sm-inline" style="color:lightseagreen; text-shadow: 3px 5px 2px cadetblue;" ><bold>RG</bold></big>
                
                </div>
            </a>

                </div>
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 min-vh-100" style="color:lightcyan; text-shadow: 3px 2px 3px cornflowerblue; margin-left: 18px;margin-top: 24px;">
                    <ul class="" id="menu" style = "padding:0;">

                        <li style = " list-style:none; color: white !important;">
                                <i class="fs-4 bi-speedometer2"></i> <h5 class="ms-1 d-none d-sm-inline" style=" text-shadow: 6px 2px 3px cornflowerblue;">Reports</h5>
                            <ul class="" id="submenu1" data-bs-parent="#menu" style="padding-left:20px; font-size:13px; font-weight:null;">
                                {% for list in list%}
                                <li class="w-100" style = "list-style:none;">
                                    <a href= {% url 'query_app:base_html_region' list.Region %} class="nav-link px-0"> 
                                        <h6 class="d-none d-sm-inline" style="color:white; text-shadow: 3px 4px 3px cornflowerblue;">  
                                            {{ list.Region }}
                                        </h6>
                                    </a>
                                </li>
                                {% endfor %}
                 
                            </ul>
                        </li>

                        {% comment %} Access for only staff or super user {% endcomment %}

                        {% if request.user.is_superuser or request.user.is_staff %}

                        <li style = " list-style:none;">
                            <a href= "#" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-table" ></i> <h5 class="ms-1 d-none d-sm-inline" style="color: white; text-shadow: 3px 2px 3px cornflowerblue;">DB Refresh</h5></a>
                        </li>
                        {% endif %}


                        {% comment %} Access for only super user {% endcomment %}
                        
                        {% if request.user.is_superuser %}

                        <li style = " list-style:none;">
                            <a href= {% url 'query_app:manage_users' %} class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-table" ></i> <h5 class="ms-1 d-none d-sm-inline" style="color: white; text-shadow: 3px 2px 3px cornflowerblue;">Manage Users</h5></a>
                        </li>

                        <li style = " list-style:none;">
                            <a href= {% url 'query_app:pending_user_request' %} class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-table" ></i> <h5 class="ms-1 d-none d-sm-inline" style="color: white; text-shadow: 3px 2px 3px cornflowerblue;">Pending Request</h5></a>
                        </li>

                        <li style = " list-style:none; color: white !important;">
                            <a href= {% url 'query_app:manage_regions' %} class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-table"></i> <h5 class="ms-1 d-none d-sm-inline" style="text-shadow: 3px 2px 3px cornflowerblue;">Manage Regions</h5></a>
                        </li>
           

                        <li style = " list-style:none;">
                            <a href= {% url 'query_app:manage_reports' %} class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-table" ></i> <h5 class="ms-1 d-none d-sm-inline" style="color: white; text-shadow: 3px 2px 3px cornflowerblue;">Manage Reports</h5></a>
                        </li>


                        

                        {% endif %}

                    </ul>
                    <hr>
                </div>
            </div>
                <div class="col py-3" style="background-color: aliceblue; position: relative;">
                    
                    {% block content %}
                    {% endblock %}

                    <div style="    position: absolute;
                    top: 8px;
                    right: 2px;
                    width: 205px; ">
                    <ul id="" style="
                        color: black;  border-radius: 12px;
                        padding: 12px 22px 10px; font-size:13px;">
                        <div style = "display: flex;
                        justify-content: end;">
                        hello, {{request.user}}
                        </div>
                        {% comment %} <a class = "" href="{% url 'query_app:base_html_Admin' %}"><li style="list-style: none;">Admin</li></a> {% endcomment %}
                        <a class = "right-section" style = "text-decoration:none; display: flex;
                        justify-content: end;" href="{% url 'query_app:logout-page' %}"><li style="list-style: none; color: black">Log Out</li></a>
                    </ul>
                </div>
            </div>
        </div>
    </div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

<!-- JQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<!-- Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>



</body>

</html>